In [1]:
print('Hello World')

Hello World


In [2]:
print('Hello Pune')
print('Good Bye!')

Hello Pune
Good Bye!


In [3]:
num = 34
name = 'Tushar'

In [4]:
print(num, name)

34 Tushar


In [7]:
print(type(num))
print(type(name))

<class 'int'>
<class 'str'>


In [8]:
num

34

In [9]:
# Addition of two numbers
num1 = 47
num2 = 53
add = num1 + num2
print('Addition is:', add)

Addition is: 100


In [10]:
# Addition of two numbers
num1 = 47
num2 = 53
add = num1 + num2
print('Addition is: %d' %add)

Addition is: 100


In [11]:
num = 56.74

In [12]:
type(num)

float

In [14]:
name1 = input('Enter first name:')
name2 = input('Enter second name:')
add = name1 + name2
print('Combined Name is:', add)

Enter first name: tushar
Enter second name: kute


Combined Name is: tusharkute


In [15]:
name1 = int(input('Enter first number:'))
name2 = int(input('Enter second number:'))
add = name1 + name2
print('Addition is:', add)

Enter first number: 34
Enter second number: 66


Addition is: 100


In [23]:
num = 45
if num > 0:
    print('Positive Number')
    print('Good Bye!')
else:
    print('Negative Number')
print('Done!')

Positive Number
Good Bye!
Done!


In [24]:
count = 0
while count < 10:
    print('Tushar')
    count += 1

Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar


In [27]:
for num in 45,22,14,35,26,41,25:
    print(num*num)

2025
484
196
1225
676
1681
625


In [28]:
def square(num):
    val = num * num
    return val

In [30]:
x = square(23)
print(x)

529


In [31]:
def calc(num):
    val1 = num * num
    val2 = num * num * num
    return val1, val2

In [32]:
print(calc(3))

(9, 27)


In [33]:
x = [34,12,54,36,78,98]

In [34]:
type(x)

list

In [35]:
x[3]

36

In [36]:
y = (34,12,54,36,78,98)

In [37]:
type(y)

tuple

In [38]:
y[3]

36

In [39]:
y[3] = 45

TypeError: 'tuple' object does not support item assignment

In [40]:
z = 34,12,54,36,78,98

In [41]:
d = {2:45, 3:67, 5:18, 10:34}

In [42]:
type(d)

dict

In [43]:
d[3]

67

In [44]:
s = {5,6,4,5,6,7,9,7,6,5,4,5,6,8}

In [45]:
type(s)

set

In [46]:
s

{4, 5, 6, 7, 8, 9}

In [47]:
s.add(5)

In [48]:
s

{4, 5, 6, 7, 8, 9}

In [49]:
s.add(3)

In [50]:
s

{3, 4, 5, 6, 7, 8, 9}

In [51]:
import math

In [52]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [53]:
math.sqrt(23)

4.795831523312719

In [54]:
math.sin(12)

-0.5365729180004349

In [55]:
math.factorial(12)

479001600

In [56]:
math.pi

3.141592653589793

In [57]:
math.e

2.718281828459045

In [58]:
import time

In [59]:
time.asctime()

'Mon Jan  6 16:24:48 2025'

In [60]:
print('Hello')
time.sleep(5)
print('World')

Hello
World


In [61]:
import math as m

In [62]:
m.log(12)

2.4849066497880004

In [63]:
m.pi

3.141592653589793

In [64]:
# selective import
from math import sin, log, pi

In [65]:
sin(12)

-0.5365729180004349

In [66]:
log(11)

2.3978952727983707

In [67]:
pi

3.141592653589793

In [73]:
class Person:                   # class
    def __init__(self, n, a):   # constructor
        self.name = n           # instance variables
        self.age = a

    def show(self):             # instance function / method
        print('Values are:', self.name, self.age)

    def isEligible(self):
        if self.age < 18:
            print('NOT eligible for driving')
        else:
            print('Eligible for driving')

In [77]:
# create the object
p1 = Person('Pooja', 23)

In [78]:
p1.show()

Values are: Pooja 23


In [79]:
p1.isEligible()

Eligible for driving


##### Array Operations

In [80]:
import numpy as np

In [82]:
x = np.arange(1,11)

In [83]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
num = np.array([56,33,12,54,37,94,62])

In [85]:
num

array([56, 33, 12, 54, 37, 94, 62])

In [86]:
num.dtype

dtype('int64')

In [87]:
M = np.array([[4,5,6],[1,2,3]])

In [88]:
M

array([[4, 5, 6],
       [1, 2, 3]])

In [89]:
M.shape

(2, 3)

In [90]:
M.size

6

In [91]:
M[1][0]

1

In [92]:
M[1,0]

1

In [93]:
M.min()

1

In [94]:
Z = np.zeros([100,100])

In [95]:
Z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [96]:
np.random.randint(1,10)

8