In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('images/sachin.jpg')

In [6]:
tx = 50  # translation-x
ty = 100 # translation-y
angle = 45    # rotation
scale = 0.8   # scaling factor
shear_x = 0.25  # tilt on x axis
shear_y = 0.3   # tilt on y axis

# define the affine transformation matrix
M = np.float32([[scale*np.cos(np.radians(angle)),   shear_x,   tx],
                [shear_y,   scale*np.sin(np.radians(angle)),   ty]])

In [7]:
img_affine = cv2.warpAffine(img,M, (img.shape[1], img.shape[0]))

In [5]:
cv2.imshow('final image', img_affine)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
M1 = np.array([[4,5,6],[1,2,3]])
M2 = np.array([[2,8,9],[0,5,7]])

In [10]:
M1

array([[4, 5, 6],
       [1, 2, 3]])

In [11]:
M2

array([[2, 8, 9],
       [0, 5, 7]])

In [12]:
np.hstack([M1, M2])

array([[4, 5, 6, 2, 8, 9],
       [1, 2, 3, 0, 5, 7]])

In [13]:
np.vstack([M2, M1])

array([[2, 8, 9],
       [0, 5, 7],
       [4, 5, 6],
       [1, 2, 3]])

In [14]:
# Original Image
img1 = cv2.resize(img, None, fx=0.5, fy=0.5)

# Affine Image
img2 = cv2.resize(img_affine, None, fx=0.5, fy=0.5)

In [15]:
final_image = np.hstack([img1, img2])

In [17]:
cv2.imshow('final image', final_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
M1 * M2

array([[ 8, 40, 54],
       [ 0, 10, 21]])

In [20]:
M1 @ M2.T

array([[102,  67],
       [ 45,  31]])